# Generated by Django 3.2 on 2022-04-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='filmworks',
        ),
        migrations.RemoveField(
            model_name='person',
            name='filmworks',
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='role',
            field=models.TextField(choices=[('актер', 'Actor'), ('директор', 'Director'), ('продюсер', 'Producer'), ('writer', 'Writer')], default='актер', verbose_name='role'),
        ),
    ]
