# Generated by Django 3.2 on 2022-04-26 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20220424_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genrefilmwork',
            name='genre',
            field=models.ForeignKey(db_column='genre_id', on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='movies.genre', verbose_name='genre'),
        ),
        migrations.AlterField(
            model_name='personfilmwork',
            name='person',
            field=models.ForeignKey(db_column='person_id', on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='movies.person', verbose_name='person'),
        ),
    ]
