# Generated by Django 3.2 on 2022-04-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20220427_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmwork',
            name='persons',
            field=models.ManyToManyField(related_name='person_filmwork', through='movies.PersonFilmwork', to='movies.Person', verbose_name='persons'),
        ),
    ]
